# Production environment overrides
database:
  host: localhost
  database: mlops-creditfraud
  pool_size: 20
  password: ${PROD_DB_PASSWORD}

logging:
  level: INFO
  console_output: false
  file_path: /var/log/mlops/prod.log

api:
  host: 0.0.0.0
  port: 8080
  workers: 8