-- Active: 1758948723040@@127.0.0.1@3306@mlops-tpcds-semi
CREATE TABLE `mlops-tpcds-semi`.customer_analytics_copy (
  c_customer_sk int DEFAULT NULL,
  c_preferred_cust_flag char(1) DEFAULT NULL,
  hd_demo_sk int DEFAULT NULL,
  hd_income_band_sk int DEFAULT NULL,
  hd_buy_potential char(15) DEFAULT NULL,
  hd_dep_count int DEFAULT NULL,
  hd_vehicle_count int DEFAULT NULL,
  cd_gender char(1) DEFAULT NULL,
  cd_marital_status char(1) DEFAULT NULL,
  cd_education_status char(20) DEFAULT NULL,
  cd_credit_rating char(10) DEFAULT NULL,
  ca_city varchar(60) DEFAULT NULL,
  ca_state char(2) DEFAULT NULL,
  ca_country varchar(20) DEFAULT NULL,
  ca_location_type char(20) DEFAULT NULL,
  has_catalog_sales bigint DEFAULT NULL,
  has_web_sales bigint DEFAULT NULL,
  has_store_sales int NOT NULL,
  catalog_sales_amount decimal(29, 2) DEFAULT NULL,
  web_sales_amount decimal(29, 2) DEFAULT NULL,
  store_sales_amount decimal(29, 2) DEFAULT NULL,
  catalog_net_profit decimal(29, 2) DEFAULT NULL,
  web_net_profit decimal(29, 2) DEFAULT NULL,
  store_net_profit decimal(29, 2) DEFAULT NULL,
  catalog_return_amount decimal(29, 2) DEFAULT NULL,
  web_return_amount decimal(29, 2) DEFAULT NULL,
  store_return_amount decimal(29, 2) DEFAULT NULL,
  total_sales_amount decimal(31, 2) DEFAULT NULL,
  total_net_profit decimal(31, 2) DEFAULT NULL,
  total_return_amount decimal(31, 2) DEFAULT NULL,
  active_channels_count bigint DEFAULT NULL,
  store_transaction_count bigint NOT NULL,
  return_rate_percentage decimal(40, 6) DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 417,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;